name: ceia_components
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  formz: ^0.7.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.19.0
  logger: ^2.2.0
  flutter_localization: ^0.2.0
  cloud_firestore: ^5.4.0
  firebase_auth: ^5.2.1
  go_router: ^14.2.7
  http: ^1.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  collection: ^1.16.0
  shared_preferences: ^2.3.2
  web: ^1.0.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  assets:
  - image/
  
  fonts:
  - family: Montserrat
    fonts:
      - asset: font/Montserrat-Regular.ttf
      - asset: font/Montserrat-Medium.ttf
      - asset: font/Montserrat-SemiBold.ttf
      - asset: font/Montserrat-Bold.ttf


